### ISSUE TITLE
Query: request list plugin

### ISSUE THREAD

**Issue by Matthieu-U** [hudmol/request_list#1]
Dear colleague,

We at the University of Amsterdam are looking into the possibilities to add the Request list plugin to our ArchivesSpace. We really like the way that Harvard has made it possible to add items to the request list and send all the requested items to our external request handling system (Topdesk).

We installed the plugin on our test server but we are having some questions we hope you might be able to answer:

1.	Is it possible to only add the “add to request list” button for items and not for the overarching levels? For example, we would like to be able to configure that not a whole ‘series’ could be added to the request list.

2.	Is it possible to not show the “add to request list” button for items that we don’t want customers to be able to request? 

3.	Is it possible to make the visibility of the “add to request” button dependent on a value in a metadata field in a resource/archival object?

4.	In Harvard’s ArchivesSpace we noticed that the “add to request list” button is visible in the top menu but also behind the items in the ‘Collection inventory’ tab. Could you perhaps explain how to add the “add to request list” buttons to the “Collections inventory”?

5.	We found more versions of the Request list plugin on Github. Could you let us know which version is best to use? 
https://github.com/hudmol/request_list or https://github.com/harvard-library/request_list. It seems like besides the Request list plugin there is also some other customized code installed. 

Many thanks in advance for your response!

Kind regards,
Matthieu Uittenbogaard

Project Manager 
University Library
University of Amsterdam
m.uittenbogaard@uva.nl

**Comment by jambun** [comment]
Hi Matthieu,

The items 1 - 4 are all possible. Most, perhaps all, would require some customization.

As for 5. I'm not sure about the current state of the Harvard deployment. We developed this for them about three years ago, along with this plugin:
https://github.com/hudmol/harvard_request_list_customizations

The harvard-library version of the request_list plugin is their fork. They seem to have modified it since they forked. I haven't looked at their changes so can't comment on them.

We would be happy to discuss a project to customize request_list for your needs.


Cheers,
James

**Comment by Matthieu-U** [comment]
Hi James,

Thank you very much for your quick response. Good to hear that all the first 4 items are possible.

In that case, we will first have a look at the Harvard request list customizations and discuss our requirements for the request workflow internally.

It would be great to discuss this with you. I will get back to you next week.

Best wishes,
Matthieu

Van: James Bullen ***@***.***>
Verzonden: dinsdag 30 november 2021 00:16
Aan: hudmol/request_list ***@***.***>
CC: Matthieu Uittenbogaard ***@***.***>; Author ***@***.***>
Onderwerp: Re: [hudmol/request_list] Query: request list plugin (Issue #1)


Hi Matthieu,

The items 1 - 4 are all possible. Most, perhaps all, would require some customization.

As for 5. I'm not sure about the current state of the Harvard deployment. We developed this for them about three years ago, along with this plugin:
https://github.com/hudmol/harvard_request_list_customizations<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhudmol%2Fharvard_request_list_customizations&data=04%7C01%7Cm.uittenbogaard%40uva.nl%7C9727944ac3e54a2a1afa08d9b38e45fb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637738245934725769%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gV3mIgwbX39M5Nwr0iGw2lEmpGkM0BL0c%2Bh6CfhbU3w%3D&reserved=0>

The harvard-library version of the request_list plugin is their fork. They seem to have modified it since they forked. I haven't looked at their changes so can't comment on them.

We would be happy to discuss a project to customize request_list for your needs.

Cheers,
James

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhudmol%2Frequest_list%2Fissues%2F1%23issuecomment-982120679&data=04%7C01%7Cm.uittenbogaard%40uva.nl%7C9727944ac3e54a2a1afa08d9b38e45fb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637738245934735763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MZdmMv1Y1kDwIpQ1sGi%2Bg52%2BwZ%2B0qvjI0%2BcycPYnUD0%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACTTMKDFIATOWYMLEJSSUU3UOQCUXANCNFSM5I7OFN3Q&data=04%7C01%7Cm.uittenbogaard%40uva.nl%7C9727944ac3e54a2a1afa08d9b38e45fb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637738245934735763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PTiFPz3rRH9yJn7aOr7iy5LLQ58GBgPWSOAMOEBATmg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cm.uittenbogaard%40uva.nl%7C9727944ac3e54a2a1afa08d9b38e45fb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637738245934745763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iJG7obbAOh1NU6eq0EyO4N4%2F8YlGBVfODwM2jBzoD7Q%3D&reserved=0> or Android<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cm.uittenbogaard%40uva.nl%7C9727944ac3e54a2a1afa08d9b38e45fb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637738245934745763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lX6bFvwatK4Xtx5gD3jigc2G1JRXtE8u6eEhEdcnK5s%3D&reserved=0>.

**Comment by Matthieu-U** [comment]
Hi James,



In the meantime we've had an internal conversation about our basic requirements.



It would be great if we - Hans Gommers (developer) and myself - could have a short meeting with you to show you around in our ArchivesSpace and to check with you if what we want is possible (and what it would involve in terms of amount of work and related costs).



Could we perhaps schedule an online meeting with you for this week or next week? What would suit you best?



Thanks in advance, and best wishes,

Matthieu


Van: James Bullen ***@***.***>
Verzonden: dinsdag 30 november 2021 00:16
Aan: hudmol/request_list ***@***.***>
CC: Matthieu Uittenbogaard ***@***.***>; Author ***@***.***>
Onderwerp: Re: [hudmol/request_list] Query: request list plugin (Issue #1)


Hi Matthieu,

The items 1 - 4 are all possible. Most, perhaps all, would require some customization.

As for 5. I'm not sure about the current state of the Harvard deployment. We developed this for them about three years ago, along with this plugin:
https://github.com/hudmol/harvard_request_list_customizations<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhudmol%2Fharvard_request_list_customizations&data=04%7C01%7Cm.uittenbogaard%40uva.nl%7C9727944ac3e54a2a1afa08d9b38e45fb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637738245934725769%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gV3mIgwbX39M5Nwr0iGw2lEmpGkM0BL0c%2Bh6CfhbU3w%3D&reserved=0>

The harvard-library version of the request_list plugin is their fork. They seem to have modified it since they forked. I haven't looked at their changes so can't comment on them.

We would be happy to discuss a project to customize request_list for your needs.

Cheers,
James

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhudmol%2Frequest_list%2Fissues%2F1%23issuecomment-982120679&data=04%7C01%7Cm.uittenbogaard%40uva.nl%7C9727944ac3e54a2a1afa08d9b38e45fb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637738245934735763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MZdmMv1Y1kDwIpQ1sGi%2Bg52%2BwZ%2B0qvjI0%2BcycPYnUD0%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACTTMKDFIATOWYMLEJSSUU3UOQCUXANCNFSM5I7OFN3Q&data=04%7C01%7Cm.uittenbogaard%40uva.nl%7C9727944ac3e54a2a1afa08d9b38e45fb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637738245934735763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PTiFPz3rRH9yJn7aOr7iy5LLQ58GBgPWSOAMOEBATmg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cm.uittenbogaard%40uva.nl%7C9727944ac3e54a2a1afa08d9b38e45fb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637738245934745763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iJG7obbAOh1NU6eq0EyO4N4%2F8YlGBVfODwM2jBzoD7Q%3D&reserved=0> or Android<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cm.uittenbogaard%40uva.nl%7C9727944ac3e54a2a1afa08d9b38e45fb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637738245934745763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lX6bFvwatK4Xtx5gD3jigc2G1JRXtE8u6eEhEdcnK5s%3D&reserved=0>.

**Comment by jambun** [comment]
Replied directly, closing.
